# Generated by Django 5.2.17 on 2026-09-06 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_expediente', models.DateField(default=datetime.date.today, help_text='Data correspondente ao expediente de controle das viaturas (única por dia)', unique=True, verbose_name='Data do Expediente')),
                ('horario_inicio', models.TimeField(default=datetime.time(7, 0), help_text='Ex: 07:00 ou 08:00', verbose_name='Horário de Início do Expediente')),
                ('horario_termino', models.TimeField(default=datetime.time(19, 0), help_text='Ex: 19:00 ou término de plantão', verbose_name='Horário de Término do Expediente')),
                ('nome_vigilante', models.CharField(help_text='Nome legível para assinatura da ficha física/digital', max_length=150, verbose_name='Nome do Vigilante / Plantonista')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('ENCERRADA', 'Encerrada')], default='ABERTA', max_length=15, verbose_name='Status da Ficha')),
                ('visto_responsavel', models.BooleanField(default=False, verbose_name='Visto do Responsável pelas Viaturas')),
                ('data_visto_responsavel', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Visto do Responsável')),
                ('visto_chefia', models.BooleanField(default=False, verbose_name='Visto da Chefia')),
                ('data_visto_chefia', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Visto da Chefia')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Gerais do Expediente')),
                ('encerrada_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Ficha de Controle Diário',
                'verbose_name_plural': 'Fichas de Controle Diário',
                'ordering': ['-data_expediente'],
            },
        ),
        migrations.CreateModel(
            name='RegistroUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condutor', models.CharField(help_text='Servidor / Policial Federal condutor do veículo', max_length=150, verbose_name='Condutor (Nome e Matrícula)')),
                ('destino', models.CharField(help_text='Destino, itinerário ou operação', max_length=200, verbose_name='Destino / Missão')),
                ('horario_saida', models.TimeField(verbose_name='Horário de Saída')),
                ('odometro_saida', models.PositiveIntegerField(verbose_name='Odômetro de Saída (KM)')),
                ('horario_chegada', models.TimeField(blank=True, null=True, verbose_name='Horário de Chegada')),
                ('odometro_chegada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odômetro de Chegada (KM)')),
                ('possui_avarias', models.BooleanField(default=False, verbose_name='Veículo Possui Avarias?')),
                ('avarias_encontradas', models.TextField(blank=True, help_text='Descreva avarias, amassados, arranhões ou problemas mecânicos encontrados', null=True, verbose_name='Espaço para Anotar as Avarias Encontradas')),
                ('status', models.CharField(choices=[('EM_TRANSITO', 'Em Trânsito / Aberto'), ('CONCLUIDO', 'Concluído / Retornou'), ('CANCELADO', 'Cancelado')], default='EM_TRANSITO', max_length=15, verbose_name='Status do Registro')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Registro de Uso / Saída de Viatura',
                'verbose_name_plural': 'Registros de Uso de Viaturas',
                'ordering': ['horario_saida', 'id'],
            },
        ),
    ]
