# Generated by Django 5.2.17 on 2026-09-06 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fichas", "0001_initial"),
        ("veiculos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fichacontrole",
            name="chefia_visto_usuario",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fichas_vistadas_chefia", to=settings.AUTH_USER_MODEL, verbose_name="Assinado por (Chefia)"),
        ),
        migrations.AddField(
            model_name="fichacontrole",
            name="encerrada_por",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fichas_encerradas_pelo_usuario", to=settings.AUTH_USER_MODEL, verbose_name="Encerrada por"),
        ),
        migrations.AddField(
            model_name="fichacontrole",
            name="responsavel_visto_usuario",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fichas_vistadas_responsavel", to=settings.AUTH_USER_MODEL, verbose_name="Assinado por (Responsável)"),
        ),
        migrations.AddField(
            model_name="fichacontrole",
            name="vigilante",
            field=models.ForeignKey(help_text="Pessoa responsável por preencher a ficha naquele dia", on_delete=django.db.models.deletion.PROTECT, related_name="fichas_preenchidas", to=settings.AUTH_USER_MODEL, verbose_name="Vigilante Responsável do Dia"),
        ),
        migrations.AddField(
            model_name="registrouso",
            name="condutor_usuario",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="viagens_como_condutor", to=settings.AUTH_USER_MODEL, verbose_name="Usuário Cadastrado do Condutor"),
        ),
        migrations.AddField(
            model_name="registrouso",
            name="ficha",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="registros", to="fichas.fichacontrole", verbose_name="Ficha Diária"),
        ),
        migrations.AddField(
            model_name="registrouso",
            name="registrado_por",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Registrado por"),
        ),
        migrations.AddField(
            model_name="registrouso",
            name="viatura",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="registros_uso", to="veiculos.viatura", verbose_name="Viatura"),
        ),
    ]
