# Generated by Django 6.0.8 on 2026-09-11 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fichas", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrouso",
            name="data_chegada",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Chegada"
            ),
        ),
        migrations.AddField(
            model_name="registrouso",
            name="data_saida",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data de Saída"
            ),
        ),
    ]
