# Generated by Django 6.0.8 on 2026-09-11 03:44

from django.db import migrations


def populate_dates(apps, schema_editor):
    RegistroUso = apps.get_model('fichas', 'RegistroUso')
    for reg in RegistroUso.objects.all():
        reg.data_saida = reg.ficha.data_expediente
        if reg.horario_chegada:
            reg.data_chegada = reg.ficha.data_expediente
        reg.save(update_fields=['data_saida', 'data_chegada'])

def reverse_dates(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_registrouso_data_chegada_registrouso_data_saida'),
    ]

    operations = [
        migrations.RunPython(populate_dates, reverse_dates),
    ]
