# Generated by Django 6.0.8 on 2026-09-12 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fichas", "0004_auto_20260910_2244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichacontrole",
            name="data_expediente",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Data correspondente ao expediente de controle das viaturas",
                verbose_name="Data do Expediente",
            ),
        ),
    ]
