# Generated by Django 6.1.1 on 2026-09-27 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fichas", "0005_alter_fichacontrole_data_expediente"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrouso",
            options={
                "ordering": ["id"],
                "verbose_name": "Registro de Uso / Saída de Viatura",
                "verbose_name_plural": "Registros de Uso de Viaturas",
            },
        ),
        migrations.AddField(
            model_name="registrouso",
            name="registro_saida_origem",
            field=models.ForeignKey(
                blank=True,
                help_text="Saída correspondente caso tenha ocorrido em ficha de outro expediente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros_retorno",
                to="fichas.registrouso",
                verbose_name="Registro de Saída de Origem",
            ),
        ),
        migrations.AddField(
            model_name="registrouso",
            name="tipo_movimentacao",
            field=models.CharField(
                choices=[
                    ("SAIDA", "Apenas Saída no Expediente"),
                    ("CHEGADA", "Apenas Retorno/Entrada no Expediente"),
                    ("COMPLETO", "Saída e Retorno no mesmo Expediente"),
                ],
                default="COMPLETO",
                help_text="Identifica se o registro é apenas de saída, apenas de retorno ou ambos",
                max_length=15,
                verbose_name="Tipo de Movimentação",
            ),
        ),
        migrations.AlterField(
            model_name="registrouso",
            name="data_saida",
            field=models.DateField(blank=True, null=True, verbose_name="Data de Saída"),
        ),
        migrations.AlterField(
            model_name="registrouso",
            name="horario_saida",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Horário de Saída"
            ),
        ),
        migrations.AlterField(
            model_name="registrouso",
            name="odometro_saida",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Odômetro de Saída (KM)"
            ),
        ),
    ]
