# Generated by Django 6.1.1 on 2026-09-28 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fichas", "0006_alter_registrouso_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fichacontrole",
            name="assinatura_vigilante",
            field=models.BooleanField(
                default=False, verbose_name="Assinatura do Vigilante"
            ),
        ),
        migrations.AddField(
            model_name="fichacontrole",
            name="data_assinatura_vigilante",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Data/Hora da Assinatura do Vigilante",
            ),
        ),
        migrations.AddField(
            model_name="fichacontrole",
            name="vigilante_assinatura_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fichas_assinadas_vigilante",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assinado por (Vigilante)",
            ),
        ),
    ]
