name: Deploy app_viaturas

on:
  workflow_dispatch:
    inputs:
      motivo:
        description: 'Motivo do deploy manual'
        required: false
        default: 'deploy manual'

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
        GIT_SSL_NO_VERIFY: "true"

      - name: Deploy em produção
        run: |
          powershell -ExecutionPolicy Bypass -File C:\scripts\deploy-app_viaturas.ps1