"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carregar variáveis de ambiente do arquivo .env na raiz do projeto (ao iniciar ou reiniciar o servidor)
try:
    load_dotenv(os.path.join(BASE_DIR, ".env"), override=True)
except (PermissionError, OSError):
    pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-kqat%!_#$wn75-(uj_c3d+51$jetu!=hopn#kanwt6^30*qtu-",
)


# Configuração de Ambiente de banco de dados: production / development
DB_ENV = os.environ.get("DB_ENV", "development").strip().lower()

if DB_ENV == "production":
    DEBUG = False
    DATABASE_NAME = str(BASE_DIR / "database" / "db_prod.sqlite3")
else:
    DB_ENV = "development"
    DEBUG = True
    DATABASE_NAME = str(BASE_DIR / "database" / "db_dev.sqlite3")

# Configuração de Ambiente de aplicação: local / operacao
APP_ENV = os.environ.get("APP_ENV", "local").strip().lower()

if APP_ENV == "local":
    DEBUG = True
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "testserver"]
    CSRF_TRUSTED_ORIGINS = ["http://localhost", "http://127.0.0.1"]
elif APP_ENV == "operacao":
    DEBUG = False
    ALLOWED_HOSTS = ["10.68.6.121"]
    CSRF_TRUSTED_ORIGINS = [
        "https://10.68.6.121",
        "https://10.68.6.121:8443",
    ]


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Apps locais do sistema
    "usuarios.apps.UsuariosConfig",
    "veiculos.apps.VeiculosConfig",
    "fichas.apps.FichasConfig",
    "dashboard.apps.DashboardConfig",
]

MIDDLEWARE = [
    "dashboard.middleware.EnvReloadMiddleware",
    "dashboard.middleware.RealIPMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATABASE_NAME,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Modelo de Usuário Customizado
AUTH_USER_MODEL = "usuarios.Usuario"

LOGIN_URL = "usuarios:login"
LOGIN_REDIRECT_URL = "dashboard:home"
LOGOUT_REDIRECT_URL = "usuarios:login"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
