# Generated by Django 6.0.8 on 2026-09-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="perfil",
        ),
    ]
