# Generated by Django 5.2.17 on 2026-09-06 20:23

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Setor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sigla", models.CharField(max_length=20, unique=True, verbose_name="Sigla")),
                ("nome", models.CharField(max_length=150, verbose_name="Nome do Setor / Delegacia")),
                ("responsavel", models.CharField(blank=True, max_length=100, null=True, verbose_name="Responsável pelo Setor")),
                ("ramal", models.CharField(blank=True, max_length=30, null=True, verbose_name="Ramal / Telefone")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Setor / Unidade",
                "verbose_name_plural": "Setores / Unidades",
                "ordering": ["sigla"],
            },
        ),
        migrations.CreateModel(
            name="Viatura",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("placa", models.CharField(help_text="Ex: ABC-1234 ou BRA2E19", max_length=10, unique=True, verbose_name="Placa")),
                ("marca", models.CharField(help_text="Ex: Toyota, Chevrolet, Ford", max_length=50, verbose_name="Marca")),
                ("modelo", models.CharField(help_text="Ex: Hilux 4x4, Trailblazer, Ranger", max_length=80, verbose_name="Modelo")),
                ("ano_fabricacao", models.PositiveIntegerField(default=2022, verbose_name="Ano Fabricação")),
                ("ano_modelo", models.PositiveIntegerField(default=2023, verbose_name="Ano Modelo")),
                ("cor", models.CharField(default="Preta", max_length=30, verbose_name="Cor")),
                ("tipo", models.CharField(choices=[("OSTENSIVA", "Caracterizada / Ostensiva"), ("DESCARACTERIZADA", "Descaracterizada / Operacional"), ("ADMINISTRATIVA", "Administrativa")], default="OSTENSIVA", max_length=25, verbose_name="Tipo de Viatura")),
                ("chassi", models.CharField(blank=True, max_length=30, null=True, verbose_name="Chassi")),
                ("status", models.CharField(choices=[("DISPONIVEL", "Disponível"), ("EM_USO", "Em Uso / Em Trânsito"), ("MANUTENCAO", "Em Manutenção"), ("INDISPONIVEL", "Indisponível")], default="DISPONIVEL", max_length=20, verbose_name="Estado do Veículo")),
                ("responsavel_tipo", models.CharField(choices=[("SETOR", "Setor"), ("PESSOA", "Servidor / Pessoa Específica")], default="SETOR", max_length=15, verbose_name="Tipo de Responsável")),
                ("responsavel_setor", models.CharField(blank=True, max_length=100, null=True, verbose_name="Setor Responsável")),
                ("km_atual", models.PositiveIntegerField(default=0, verbose_name="Quilometragem Atual (KM)")),
                ("proxima_manutencao_km", models.PositiveIntegerField(blank=True, help_text="Quilometragem limite para a próxima revisão", null=True, verbose_name="Próxima Manutenção por KM")),
                ("proxima_manutencao_data", models.DateField(blank=True, help_text="Data limite para a próxima revisão", null=True, verbose_name="Próxima Manutenção por Data")),
                ("observacoes", models.TextField(blank=True, null=True, verbose_name="Observações e Avarias Históricas")),
                ("ativo", models.BooleanField(default=True, verbose_name="Viatura Ativa na Frota")),
                ("data_cadastro", models.DateTimeField(auto_now_add=True, verbose_name="Data de Cadastro")),
                ("responsavel_pessoa", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="viaturas_sob_responsabilidade", to=settings.AUTH_USER_MODEL, verbose_name="Servidor Responsável")),
                ("setor_pertencente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="viaturas", to="veiculos.setor", verbose_name="Unidade / Setor Pertencente")),
            ],
            options={
                "verbose_name": "Viatura",
                "verbose_name_plural": "Viaturas",
                "ordering": ["modelo", "placa"],
            },
        ),
        migrations.CreateModel(
            name="Manutencao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("PREVENTIVA", "Preventiva Programada"), ("CORRETIVA", "Corretiva / Reparo Mecânico"), ("REVISAO", "Revisão Periódica / Garantia"), ("SINISTRO", "Funilaria / Sinistro / Danos")], default="PREVENTIVA", max_length=20, verbose_name="Tipo de Manutenção")),
                ("data_manutencao", models.DateField(default=datetime.date.today, verbose_name="Data do Serviço")),
                ("km_no_momento", models.PositiveIntegerField(verbose_name="Odômetro na Manutenção (KM)")),
                ("fornecedor_oficina", models.CharField(max_length=150, verbose_name="Oficina / Fornecedor Contratado")),
                ("numero_ordem_servico", models.CharField(blank=True, max_length=60, null=True, verbose_name="Nº Ordem de Serviço / Nota Fiscal")),
                ("descricao_servico", models.TextField(verbose_name="Descrição dos Serviços Realizados")),
                ("pecas_substituidas", models.TextField(blank=True, null=True, verbose_name="Peças e Componentes Substituídos")),
                ("valor_total", models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Valor Total (R$)")),
                ("proxima_revisao_km", models.PositiveIntegerField(blank=True, null=True, verbose_name="Agendar Próxima Revisão (KM)")),
                ("proxima_revisao_data", models.DateField(blank=True, null=True, verbose_name="Agendar Próxima Revisão (Data)")),
                ("data_registro", models.DateTimeField(auto_now_add=True, verbose_name="Data de Registro no Sistema")),
                ("registrado_por", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Registrado por")),
                ("viatura", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="manutenções", to="veiculos.viatura", verbose_name="Viatura")),
            ],
            options={
                "verbose_name": "Registro de Manutenção",
                "verbose_name_plural": "Registros de Manutenção",
                "ordering": ["-data_manutencao", "-data_registro"],
            },
        ),
    ]
