# Generated by Django 6.0.8 on 2026-09-11 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manutencao",
            name="viatura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manutencoes",
                to="veiculos.viatura",
                verbose_name="Viatura",
            ),
        ),
    ]
