# Generated by Django 6.1.1 on 2026-10-08 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0002_alter_manutencao_viatura"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoConsultaPlaca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consulta_habilitada",
                    models.BooleanField(
                        default=True, verbose_name="Consulta externa habilitada"
                    ),
                ),
                (
                    "provedor_ativo",
                    models.CharField(
                        choices=[
                            ("GRATUITO", "API gratuita (plano de testes / gratuito)"),
                            ("SERPRO", "API do Serpro (convênio institucional)"),
                        ],
                        default="GRATUITO",
                        max_length=10,
                        verbose_name="Provedor ativo",
                    ),
                ),
                (
                    "proxy_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ex: http://proxy.pf.gov.br:8080 (vazio = usa HTTPS_PROXY do ambiente)",
                        max_length=200,
                        verbose_name="Proxy institucional",
                    ),
                ),
                (
                    "timeout_segundos",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Timeout (segundos)"
                    ),
                ),
                (
                    "cache_dias",
                    models.PositiveSmallIntegerField(
                        default=90, verbose_name="Validade do cache (dias)"
                    ),
                ),
                (
                    "gratuito_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Use {placa} (e {token}, se o token for passado na URL). Ex: https://api.exemplo.com.br/placa/{placa}",
                        max_length=300,
                        verbose_name="URL da consulta",
                    ),
                ),
                (
                    "gratuito_token",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="Token de acesso",
                    ),
                ),
                (
                    "gratuito_cabecalho",
                    models.CharField(
                        blank=True,
                        default="Authorization",
                        help_text="Vazio = não envia cabeçalho (token na URL)",
                        max_length=60,
                        verbose_name="Cabeçalho do token",
                    ),
                ),
                (
                    "gratuito_prefixo",
                    models.CharField(
                        blank=True,
                        default="Bearer ",
                        help_text="Ex: 'Bearer ' ou vazio",
                        max_length=30,
                        verbose_name="Prefixo do token",
                    ),
                ),
                (
                    "serpro_url_token",
                    models.CharField(
                        blank=True,
                        default="https://gateway.apiserpro.serpro.gov.br/token",
                        max_length=300,
                        verbose_name="URL de obtenção do token",
                    ),
                ),
                (
                    "serpro_url_consulta",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Conforme o contrato/serviço contratado. Use {placa}.",
                        max_length=300,
                        verbose_name="URL da consulta",
                    ),
                ),
                (
                    "serpro_consumer_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Consumer Key",
                    ),
                ),
                (
                    "serpro_consumer_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Consumer Secret",
                    ),
                ),
                ("falhas_consecutivas", models.PositiveIntegerField(default=0)),
                ("circuito_aberto_ate", models.DateTimeField(blank=True, null=True)),
                ("ultimo_sucesso", models.DateTimeField(blank=True, null=True)),
                ("ultima_falha", models.DateTimeField(blank=True, null=True)),
                (
                    "ultimo_erro",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração da Consulta de Placa",
                "verbose_name_plural": "Configuração da Consulta de Placa",
            },
        ),
        migrations.CreateModel(
            name="PlacaConsultada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=8, unique=True, verbose_name="Placa"),
                ),
                ("marca", models.CharField(max_length=80, verbose_name="Marca")),
                ("modelo", models.CharField(max_length=120, verbose_name="Modelo")),
                (
                    "cor",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="Cor"
                    ),
                ),
                (
                    "ano",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Ano"
                    ),
                ),
                (
                    "provedor",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Provedor"
                    ),
                ),
                (
                    "consultado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Consultado em"),
                ),
            ],
            options={
                "verbose_name": "Placa Consultada (cache)",
                "verbose_name_plural": "Placas Consultadas (cache)",
                "ordering": ["-consultado_em"],
            },
        ),
        migrations.AddField(
            model_name="viatura",
            name="classificacao",
            field=models.CharField(
                choices=[
                    ("FROTA", "Frota da Unidade"),
                    ("EXTERNA", "Veículo Externo (não pertence à frota)"),
                    ("PENDENTE", "Aguardando Classificação"),
                ],
                db_index=True,
                default="FROTA",
                max_length=10,
                verbose_name="Classificação",
            ),
        ),
        migrations.AddField(
            model_name="viatura",
            name="classificado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Classificado em"
            ),
        ),
        migrations.AddField(
            model_name="viatura",
            name="classificado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="viaturas_classificadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Classificado por",
            ),
        ),
        migrations.AddField(
            model_name="viatura",
            name="divergencia_dados",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Preenchido quando a consulta externa retorna marca/modelo diferentes do informado manualmente",
                verbose_name="Divergência com a Consulta Externa",
            ),
        ),
        migrations.AddField(
            model_name="viatura",
            name="origem_dados",
            field=models.CharField(
                choices=[
                    ("CADASTRO", "Cadastro interno"),
                    ("API", "Consulta externa por placa"),
                    ("MANUAL", "Preenchimento manual (contingência)"),
                ],
                default="CADASTRO",
                max_length=10,
                verbose_name="Origem de Marca/Modelo",
            ),
        ),
        migrations.AddField(
            model_name="viatura",
            name="provedor_consulta",
            field=models.CharField(
                blank=True,
                default="",
                max_length=30,
                verbose_name="Provedor da Consulta",
            ),
        ),
        migrations.AddField(
            model_name="viatura",
            name="responsavel_cargo",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Cargo do Responsável",
            ),
        ),
        migrations.AddField(
            model_name="viatura",
            name="responsavel_nome",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Nome do Responsável",
            ),
        ),
        migrations.AlterField(
            model_name="viatura",
            name="setor_pertencente",
            field=models.ForeignKey(
                blank=True,
                help_text="Obrigatório para veículos classificados como frota",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="viaturas",
                to="veiculos.setor",
                verbose_name="Unidade / Setor Pertencente",
            ),
        ),
    ]
