# Generated by Django 6.0.8 on 2026-09-12 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Ex: operacao_diaria, frota, usuarios",
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        default="fas fa-cube",
                        max_length=60,
                        verbose_name="Ícone (FontAwesome)",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem no menu"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Módulo",
                "verbose_name_plural": "Módulos",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="LogAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NEGADO", "Acesso negado"),
                            ("ATRIBUICAO", "Perfil atribuído"),
                            ("REMOCAO", "Perfil removido"),
                        ],
                        max_length=15,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "acao_tentada",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ação tentada"
                    ),
                ),
                (
                    "rota",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Rota / URL"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                ("detalhe", models.TextField(blank=True, verbose_name="Detalhe")),
                (
                    "registrado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registrado em"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_acesso",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Acesso",
                "verbose_name_plural": "Logs de Acesso",
                "ordering": ["-registrado_em"],
            },
        ),
        migrations.CreateModel(
            name="Acao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome legível")),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Ex: criar, editar, exportar_pdf, apor_visto_chefia",
                        verbose_name="Código da ação",
                    ),
                ),
                (
                    "codigo_completo",
                    models.CharField(
                        editable=False,
                        help_text="Gerado automaticamente. Ex: frota.viaturas.editar",
                        max_length=200,
                        unique=True,
                        verbose_name="Código completo",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tela", "Acesso a tela / rota"),
                            ("acao", "Ação / botão dentro de uma tela"),
                            ("dado", "Visibilidade de dado / widget"),
                        ],
                        default="acao",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acoes",
                        to="accesscontrol.modulo",
                        verbose_name="Módulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ação",
                "verbose_name_plural": "Ações",
                "ordering": ["modulo__ordem", "submodulo__ordem", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "acoes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="perfis",
                        to="accesscontrol.acao",
                        verbose_name="Ações permitidas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Acesso",
                "verbose_name_plural": "Perfis de Acesso",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Ex: metricas_frota, alertas_manutencao",
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de exibição"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "modulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accesscontrol.modulo",
                        verbose_name="Módulo relacionado",
                    ),
                ),
                (
                    "perfis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="widgets",
                        to="accesscontrol.perfil",
                        verbose_name="Perfis com acesso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget do Dashboard",
                "verbose_name_plural": "Widgets do Dashboard",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Submodulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Único dentro do módulo. Ex: viaturas, manutencao",
                        verbose_name="Código",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submodulos",
                        to="accesscontrol.modulo",
                        verbose_name="Módulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submódulo",
                "verbose_name_plural": "Submódulos",
                "ordering": ["ordem", "nome"],
                "unique_together": {("modulo", "codigo")},
            },
        ),
        migrations.AddField(
            model_name="acao",
            name="submodulo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acoes",
                to="accesscontrol.submodulo",
                verbose_name="Submódulo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="acao",
            unique_together={("modulo", "submodulo", "codigo")},
        ),
        migrations.CreateModel(
            name="UsuarioPerfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atribuido_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Atribuído em"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "atribuido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atribuído por",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accesscontrol.perfil",
                        verbose_name="Perfil",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfis_atribuidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil do Usuário",
                "verbose_name_plural": "Perfis dos Usuários",
                "ordering": ["-atribuido_em"],
                "unique_together": {("usuario", "perfil")},
            },
        ),
    ]
