# Generated by Django 6.1.1 on 2026-09-14 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accesscontrol", "0002_seed_perfis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.PositiveIntegerField(
                        choices=[
                            (1001, "1001 — Login realizado com sucesso"),
                            (1002, "1002 — Logout efetuado"),
                            (
                                1003,
                                "1003 — Falha de autenticação (credenciais inválidas)",
                            ),
                            (1004, "1004 — Alteração de senha de usuário"),
                            (
                                2001,
                                "2001 — Acesso indevido bloqueado por falta de permissão (403)",
                            ),
                            (2002, "2002 — Atribuição de perfil a usuário"),
                            (2003, "2003 — Remoção de perfil de usuário"),
                            (2004, "2004 — Desativação de usuário"),
                            (2005, "2005 — Ativação de usuário"),
                            (3001, "3001 — Cadastro de viatura"),
                            (3002, "3002 — Edição de dados da viatura"),
                            (3003, "3003 — Alteração de status da viatura"),
                            (3004, "3004 — Desativação de viatura da frota"),
                            (3010, "3010 — Registro de manutenção de viatura"),
                            (3011, "3011 — Edição de registro de manutenção"),
                            (4001, "4001 — Abertura de ficha de controle"),
                            (4002, "4002 — Edição de dados da ficha"),
                            (4003, "4003 — Encerramento de ficha de controle"),
                            (4010, "4010 — Registro de saída de viatura"),
                            (4011, "4011 — Registro de retorno de viatura"),
                            (4012, "4012 — Edição de movimentação de viatura"),
                            (4020, "4020 — Aposição de visto NUTRAN na ficha"),
                            (4021, "4021 — Aposição de visto da Chefia na ficha"),
                            (4030, "4030 — Exportação de ficha em PDF"),
                            (4031, "4031 — Exportação de ficha em Excel"),
                            (5001, "5001 — Cadastro de novo usuário"),
                            (5002, "5002 — Edição de dados cadastrais de usuário"),
                            (9001, "9001 — Erro interno do servidor (HTTP 500)"),
                            (9002, "9002 — Requisição inválida (HTTP 400)"),
                        ],
                        db_index=True,
                        verbose_name="Código da Ação",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição da Ação"),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Categoria"
                    ),
                ),
                (
                    "usuario_repr",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Identificação do Usuário",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="URL Acessada"
                    ),
                ),
                (
                    "metodo_http",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Método HTTP"
                    ),
                ),
                (
                    "status_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Status HTTP"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "objeto_repr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Objeto Afetado"
                    ),
                ),
                (
                    "objeto_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID do Objeto"
                    ),
                ),
                (
                    "tabela_afetada",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tabela / Model"
                    ),
                ),
                (
                    "detalhes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Detalhes da Alteração"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data e Hora"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_auditoria",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["codigo", "-criado_em"],
                        name="accesscontr_codigo_97630e_idx",
                    ),
                    models.Index(
                        fields=["usuario", "-criado_em"],
                        name="accesscontr_usuario_d6ad2c_idx",
                    ),
                ],
            },
        ),
    ]
